# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.otips.me
title: Gabriel's Blog
subtitle: A blog to record tips and ideas in my life.
author:
    name: Gabriel Zhang
    email: smalldirector@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

markdown: rdiscount
highlighter: true
permalink: /posts/:title.html
rdiscount:
    extensions: [smart]

# Disqus Comments
disqus_short_name: otips
# Google Analytics
google_analytics_tracking_id: UA-46712710-1
# JiaThis Share
jiathis_uid: 1958092

