# Site settings
title: Tips &amp;&amp; Ideas
subtitle: A blog to record tips and ideas in my life.
author: Gabriel Zhang
email: smalldirector@yahoo.com

url: http://www.otips.me # the base hostname & protocol for your site

# Build settings
markdown: rdiscount
highlighter: pygments
paginate: 5

# Google Analytics
google_analytics_tracking_id: UA-46712710-1
